config/routes.rb
Registrame::Application.routes.draw do

  
  devise_for :users, :path_names => { 
    :sign_in => 'login', :sign_out => 'logout', :password => 'secret',
    :confirmation => 'verification', :unlock => 'unlock', :sign_up => 'signup'
    }

  resources :interests
  resources :companies
  resources :attendee_types
  resources :attendees do
    member do
      get 'namebadge'
    end
  end
  resources :labels
  resources :preferences
  resources :states
  resources :countries
  resources :reports
  resources :imports do
    member do
      post 'import'
      get 'import'
    end
  end

  match 'pages/companies_autocomplete' => 'pages#companies_autocomplete', :as => :companies_autocomplete
  match 'reports/export' => 'reports#export_csv', :as => :report_export

  root :to => 'pages#index'

end

app/models/attendee.rb
class Attendee

  include DataMapper::Resource

  property :id, Serial
  property :first_name, String, :length => 80, :required => true, :index => [:full_name]
  property :last_name, String, :length => 80, :required => true, :index => [:full_name]
  property :email, String, :length => 80, :required => true, :unique => true, :index => true
  property :phone, String, :required => false
  property :job, String, :length => 100
  property :address, String, :length => 100, :required => false
  property :city, String, :required => false, :index => [:city]
  property :printed, Boolean, :default => false, :index => true
  
  
  validates_presence_of :first_name, :last_name, :email
  validates_format_of :email, :as => :email_address
  # validates_numericality_of :phone, :allow_nil => true, :allow_blank => true
  
  belongs_to :state, :required => false
  belongs_to :country, :required => false
  belongs_to :attendee_type, :required => false
  belongs_to :company, required: false
  
  has n, :interests, :through => Resource

  def full_name
    [first_name, last_name].join(' ')
  end
  
  def to_param
    [id, first_name.to_slug, last_name.to_slug].join('-')
  end
  
  def company_name
    self.company.name if company
  end

  def company_name=(name)
    self.company = Company.first_or_create(name: name) unless name.blank?
  end

  def country_name
    self.country.name if country
  end

  def country_name=(name)
    self.country = Country.first_or_create(name: name) unless name.blank?
  end

  def state_name
    self.state.name if state
  end

  def state_name=(name)
    self.state = State.first_or_create(name: name) unless name.blank?
  end

  def registration_type
    self.attendee_type.name if attendee_type
  end

  def registration_type=(id)
    self.attendee_type = AttendeeType.first(id: id)
  end

  def registration=(name)
    self.attendee_type = AttendeeType.first_or_create(name: name) unless name.blank?
  end

  def registration
    self.attendee_type.name if attendee_type
  end

  def self.printed_badges
    count(printed: true)
  end

  def self.printed
    all(printed: true)
  end
  
end

app/models/attendee_type.rb
class AttendeeType

  include DataMapper::Resource

  property :id, Serial
  property :name, String, :required => true
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has n, :attendees

  def to_param
    [id, name.to_slug].join('-')
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!

  before_filter :get_attendee, only: [:show, :edit, :update, :destroy, :namebadge]

  def index
    direction = params[:sSortDir_0] || "asc"
    @attendees = Attendee.all(
      :last_name.like => "%#{params[:sSearch]}%", limit: params[:iDisplayLength].to_i,
      offset: params[:iDisplayStart].to_i, order: [:last_name.send(direction)]
    )
    @iTotalRecords = Attendee.count
    @iTotalDisplayRecords = Attendee.count(:last_name.like => "%#{params[:sSearch]}%")
    @sEcho = params[:sEcho].to_i
    respond_with @attendees
  end

  def show
  end

  def new
    @attendee = Attendee.new
    @attendee_types = AttendeeType.all(order: [:name.asc])
  end

  def create
    @attendee = Attendee.new(params[:attendee])
    @attendee_types = AttendeeType.all(order: [:name.asc])
    if @attendee.save
      redirect_to attendee_path(@attendee), notice: 'Attendee successfully created.'
    else
      render :new, error: 'Please correct any errors present.'
    end
  end

  def edit
    @attendee_types = AttendeeType.all(order: [:name.asc])
  end

  def update
    @attendee_types = AttendeeType.all(order: [:name.asc])
    if @attendee.update(params[:attendee])
      redirect_to attendee_path(@attendee), notice: 'Attendee successfully updated.'
    else
      render :edit, error: 'Please correct any errors present.'
    end
  end

  def destroy
    @attendee.destroy
    redirect_to attendees_path
  end

  def namebadge
    @doc = PdfDocument.new(cookies[:label_format].split('&'), cookies[:label_margins].split('&'), cookies[:label_font_size].to_i)
    @doc.create_label(@attendee, cookies[:qrcode].to_s, cookies[:label_contents].split('&'), cookies[:qrcode_contents].split('&'))

    # redirect_to root_path+"/public/uploads/labels/#{@attendee.to_param}.pdf"
    redirect_to root_path+"uploads/labels/#{@attendee.to_param}.pdf"
    @attendee.update(printed: true)
  end

  private
  def get_attendee
    @attendee = Attendee.get(params[:id].to_i)
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper

  def address_data(attendee)
    str = []
    [attendee.address, attendee.city, attendee.state_name, attendee.country_name].each do |attr|
      str << attr unless attr.blank?
    end
    return str.join(', ')
  end

  def email_phone(attendee)
    str = []
    [attendee.email, number_to_phone(attendee.phone, area_code: true)].each do |attr|
      str << attr unless attr.blank?
    end
    return str.join(' | ')
  end
end

app/views/attendees/_form.html.haml
- if @attendee.errors.any?
  %div{:class => "alert-message block-message error fade in", :data => {:alert => "alert"}}
    %a{:href => "#", :class => "close"}x
    %ul
    - @attendee.errors.full_messages.each do |error|
      %li= error
%div.clearfix
  = f.label :registration_type
  %div.input
    = f.select :registration_type, options_from_collection_for_select(@attendee_types, "id", "name", @attendee.attendee_type_id)
%div.clearfix
  = f.label :first_name
  %div.input
    = f.text_field :first_name
%div.clearfix
  = f.label :last_name
  %div.input
    = f.text_field :last_name
%div.clearfix
  = f.label :email
  %div.input
    = f.text_field :email
%div.clearfix
  = f.label :phone
  %div.input
    = f.text_field :phone
%div.clearfix
  = f.label 'Job title'
  %div.input
    = f.text_field :job
%div.clearfix
  = f.label 'Company'
  %div.input
    = f.text_field :company_name
%div.clearfix
  = f.label :address
  %div.input
    = f.text_field :address
%div.clearfix
  = f.label :city
  %div.input
    = f.text_field :city
%div.clearfix
  = f.label 'State'
  %div.input
    = f.text_field :state_name
%div.clearfix
  = f.label 'Country'
  %div.input
    = f.text_field :country_name

app/views/attendees/edit.html.haml
%div.form.grid_12
  = form_for @attendee do |f|
    %fieldset
      %legend Edit Attendee
      = render partial: 'form', locals: { f: f }
      .actions
        = f.submit 'Update Attendee', class: 'btn primary'

app/views/attendees/index.html.haml
%div.page-header.grid_12
  %h2
    Attendees
    %span.prefix_4
      = link_to 'Add Attendee', new_attendee_path, class: 'btn primary small extrapad'
%div#companies
  %table.attendees-table
    %thead
      %tr
        %th Name
    %tbody
      %tr
        %td JSON

app/views/attendees/new.html.haml
%div.form.grid_12
  = form_for @attendee do |f|
    %fieldset
      %legend Register Attendee
      = render partial: 'form', locals: { f: f }
      .actions
        = f.submit 'Register Attendee', class: 'btn primary'

app/views/attendees/show.html.haml
%h2= @attendee.full_name
%div#attendee-info
  %p= email_phone(@attendee)
  %p= @attendee.registration_type
  %p
    = @attendee.job
    %br/
    = @attendee.company_name
    %br/
    = address_data(@attendee)
%div.actions
  - if cookies[:label] == "true"
    = link_to 'Print Badge', namebadge_attendee_path(@attendee), class: 'btn primary'
  = link_to 'Edit', edit_attendee_path(@attendee), class: 'btn'
  = link_to 'Delete', attendee_path(@attendee), method: :delete, confirm: 'Are you sure you want to delete this attendee?', class: 'btn danger'