config/routes.rb
Registrame::Application.routes.draw do

  
  devise_for :users, :path_names => { 
    :sign_in => 'login', :sign_out => 'logout', :password => 'secret',
    :confirmation => 'verification', :unlock => 'unlock', :sign_up => 'signup'
    }

  resources :interests
  resources :companies
  resources :attendee_types
  resources :attendees do
    member do
      get 'namebadge'
    end
  end
  resources :labels
  resources :preferences
  resources :states
  resources :countries
  resources :reports
  resources :imports do
    member do
      post 'import'
      get 'import'
    end
  end

  match 'pages/companies_autocomplete' => 'pages#companies_autocomplete', :as => :companies_autocomplete
  match 'reports/export' => 'reports#export_csv', :as => :report_export

  root :to => 'pages#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :users, :dependent => :destroy

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :json, :html
  before_filter :authenticate_user!

  before_filter :find_company, only: [:show, :edit, :update, :destroy]

  def index
    direction = params[:sSortDir_0] || "asc"
    @companies = Company.all(
      :name.like => "%#{params[:sSearch]}%", limit: params[:iDisplayLength].to_i,
      offset: params[:iDisplayStart].to_i, order: [:name.send(direction)]
    )
    @iTotalRecords = Company.count
    @iTotalDisplayRecords = Company.count(:name.like => "%#{params[:sSearch]}%")
    @sEcho = params[:sEcho].to_i
    respond_with @companies
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to @company, notice: 'Company successfully created.'
    else
      render :new, error: 'There was an error saving a new company, please try again.'
    end
  end

  def show
    @company_attendees = @company.attendees
  end

  def edit

  end

  def update
    if @company.update(params[:company])
      redirect_to company_path(@company), :notice => 'Company has been successfully updated.'
    else
      render 'edit', :error => 'An error ocurred, please check all mandatory fields.'
    end
  end

  def destroy
    @company.destroy

    redirect_to companies_path, :notice => 'Company has been successfully deleted.'
  end

  private

  def find_company
    @company = Company.get(params[:id].to_i)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.haml
%tr
  %td
    .grid_6.alpha
      %h6= link_to company.name, company_path(company)
      %p
        = pluralize(company.attendees.count, 'record')
    .grid_4.omega
      = link_to "Edit", edit_company_path(company), class: "btn"
      = link_to "Delete", company_path(company), method: :delete, confirm: 'Are you sure you want to delete this?', class: "btn danger"

app/views/companies/index.html.haml
%div.page-header.grid_12
  %h2
    Companies
    %span.prefix_4
      = link_to 'Add Company', new_company_path, class: 'btn primary small extrapad'
%div#companies
  %table.companies-table
    %thead
      %tr
        %th Name
    %tbody
      %tr
        %td JSON

app/views/companies/new.html.haml
%div.new-form.grid_12
  = form_for @company do |f|
    %fieldset
      %legend Add Company
      %div.clearfix
        = f.label :name
        %div.input
          = f.text_field :name
      .actions
        = f.submit 'Create Company', class: 'btn primary'

app/views/companies/show.html.haml
%h2= @company.name

%div#company-attendees
  %table
    %thead
      %th Name
      %th Email
      %th Actions
    %tbody
      - @company_attendees.each do |attendee|
        %tr
          %td
            = link_to attendee.full_name, attendee_path(attendee)
          %td
            = attendee.email
          %td
            = link_to 'Print Badge', namebadge_attendee_path(attendee), class: 'btn primary'
            = link_to "Delete", attendee_path(attendee), method: :delete, confirm: "Are you sure?", class: "btn danger"