config/routes.rb
Registrame::Application.routes.draw do

  
  devise_for :users, :path_names => { 
    :sign_in => 'login', :sign_out => 'logout', :password => 'secret',
    :confirmation => 'verification', :unlock => 'unlock', :sign_up => 'signup'
    }

  resources :interests
  resources :companies
  resources :attendee_types
  resources :attendees do
    member do
      get 'namebadge'
    end
  end
  resources :labels
  resources :preferences
  resources :states
  resources :countries
  resources :reports
  resources :imports do
    member do
      post 'import'
      get 'import'
    end
  end

  match 'pages/companies_autocomplete' => 'pages#companies_autocomplete', :as => :companies_autocomplete
  match 'reports/export' => 'reports#export_csv', :as => :report_export

  root :to => 'pages#index'

end

app/controllers/attendee_types_controller.rb
class AttendeeTypesController < ApplicationController
  respond_to :html, :js
  before_filter :authenticate_user!

  before_filter :find_attendee_type, only: [:show, :edit, :update, :destroy]
  
  def index
    @attendee_types = AttendeeType.all
    @attendee_type = AttendeeType.new
  end

  def show

  end

  def new
    @attendee_type = AttendeeType.new
  end

  def create
    @attendee_type = AttendeeType.new(params[:attendee_type])
    if @attendee_type.save
      redirect_to attendee_types_path, notice: 'Attendee Type successfully created.'
    else
      render :new, error: 'Please correct any errors present.'
    end
  end

  def edit

  end

  def update
    if @attendee_type.update(params[:attendee_type])
      redirect_to attendee_types_path, notice: 'Attendee Type successfully updated'
    else
      render :edit, error: 'Please check any errors present.'
    end
  end

  def destroy
    @attendee_type.destroy
    redirect_to attendee_types_path, notice: 'Attendee Type successfully deleted'
  end

  private
  def find_attendee_type
    @attendee_type = AttendeeType.get(params[:id].to_i)
  end
end

app/helpers/attendee_types_helper.rb
module AttendeeTypesHelper
end

app/views/attendee_types/_attendee_type.html.haml
.row.grid_12
  .grid_4
    = attendee_type.name
  .grid_4
    = link_to "Edit", edit_attendee_type_path(attendee_type), class: "btn"
    = link_to "Delete", attendee_type_path(attendee_type), method: :delete, confirm: 'Are you sure you want to delete this?', class: "btn danger"

app/views/attendee_types/edit.html.haml
%div#edit-form.grid_12
  = form_for @attendee_type do |f|
    %fieldset
      %legend Edit Attendee type
      %div.clearfix
        = f.label :name
        %div.input
          = f.text_field :name
          = f.submit "Update", class: "btn primary"

app/views/attendee_types/index.html.haml
%div#add-form.grid_12
  = form_for(@attendee_type, remote: true) do |f|
    %fieldset
      %legend Add new attendee type
      %div.clearfix
        = f.label :name
        %div.input
          = f.text_field :name
          = f.submit "Add type", class: "btn primary"

%h2.page-header.grid_12 Attendee types
%div#attendee-types
  = render @attendee_types

app/views/attendee_types/index.js.erb
$('#attendee-types').html("<%= escape_javascript(render @attendee_types)%>");
$('div.row:last').effect('highlight', {}, 2000);
$('#attendee_type_name').val("").focus();