config/routes.rb
Registrame::Application.routes.draw do

  
  devise_for :users, :path_names => { 
    :sign_in => 'login', :sign_out => 'logout', :password => 'secret',
    :confirmation => 'verification', :unlock => 'unlock', :sign_up => 'signup'
    }

  resources :interests
  resources :companies
  resources :attendee_types
  resources :attendees do
    member do
      get 'namebadge'
    end
  end
  resources :labels
  resources :preferences
  resources :states
  resources :countries
  resources :reports
  resources :imports do
    member do
      post 'import'
      get 'import'
    end
  end

  match 'pages/companies_autocomplete' => 'pages#companies_autocomplete', :as => :companies_autocomplete
  match 'reports/export' => 'reports#export_csv', :as => :report_export

  root :to => 'pages#index'

end

app/views/layouts/_navigation.html.haml
%nav.topbar
  .topbar-inner
    .container_12.container
      %h3= link_to ":registra.me", root_path
      %ul.nav
        - if current_user
          %li{class: "dropdown", data: {dropdown: "dropdown"}}
            = link_to "Configuration", "#", class: "dropdown-toggle"
            %ul.dropdown-menu
              %li= link_to "Attendee types", attendee_types_path
              %li= link_to "Import attendees", imports_path
              %li= link_to "Namebadge properties", label_path(Label.first)
              %li.divider
              %li= link_to "Preferences", preference_path(Preference.first)
          %li= link_to "Attendees", attendees_path
          %li= link_to "Companies", companies_path
          %li= link_to "Reports", reports_path
      %ul.nav.secondary-nav
        - if current_user
          %li{:class => "dropdown", :data => {:dropdown => "dropdown"}}
            = link_to current_user.email, "#", class: "dropdown-toggle"
            %ul.dropdown-menu
              %li= link_to "Edit my account", edit_user_registration_path
              %li.divider
              %li= link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta
    %title Registrame
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    %noscript
      %link{:rel => "stylesheet", :href => "/stylesheets/mobile.min.css"}
    :javascript
      var ADAPT_CONFIG = {
        // Where is your CSS?
        // path: 'css/',
        path: '/stylesheets/',

        // false = Only run once, when page first loads.
        // true = Change on window resize and page tilt.
        dynamic: true,

        // First range entry is the minimum.
        // Last range entry is the maximum.
        // Separate ranges by "to" keyword.
        range: [
          '0px    to 760px  = mobile.min.css',
          '760px  to 980px  = 720.min.css',
          '980px  to 1280px = 960.min.css',
          '1280px to 1600px = 1200.min.css',
          '1600px to 1940px = 1560.min.css',
          '1940px to 2540px = 1920.min.css',
          '2540px           = 2520.min.css'
        ]
      };
    %script{:src => "/javascripts/adapt.min.js"}
    = csrf_meta_tags
  %body
    %header.topbar-wrapper
      = render partial: "layouts/navigation"

    #alerts.container_12
      #flash.grid_12
        - flash.each do |key, value|
          %div{:class => "alert-message block-message #{key == :notice ? 'success' : key} fade in", :data => {:alert => "alert"}}
            %a{:href => "#", :class => "close"}x
            = value
    #page.container_12
      = yield